import type { TemplateDefinition } from './types';

/**
 * The template catalogue.
 *
 * Six design languages, not six colour schemes. A menswear store and a mobile
 * shop should not be the same website — so they differ in type, density, grid,
 * card shape, product-detail layout and which sections exist at all.
 *
 * Font stacks reference CSS custom properties the storefront app defines once
 * (`--font-sans`, `--font-serif`, …) and loads with `next/font`, so a template
 * change never costs a round trip to a font CDN at render time.
 *
 * ── Adding a template ──────────────────────────────────────────────────────
 * Append an entry. Never edit the `sections[].id` of a published template: a
 * merchant's stored customisation refers to those ids. To change a template's
 * structure, publish it as a new `version` (see `resolve.ts`).
 */
export const TEMPLATES: readonly TemplateDefinition[] = [
  // ═══════════════════════════════════════════════════════════ urban luxe ══
  {
    id: 'urban-luxe',
    name: 'Urban Luxe',
    version: 1,
    group: 'Fashion',
    tagline: 'Editorial menswear with a runway opening',
    description:
      'Full-bleed imagery, oversized type and a tall portrait grid. Built for a store that ' +
      'wants its clothes to look like a lookbook rather than a listing page.',
    businessTypes: ["Men's Wear", 'Menswear', 'Footwear', 'Sports', 'General Retail'],
    swatches: ['#12100e', '#c8a97e', '#f4f1ec'],
    badges: ['Popular', 'Premium'],
    theme: {
      primaryColor: '#12100e',
      accentColor: '#c8a97e',
      surfaceColor: '#f7f5f1',
      contentColor: '#12100e',
      radius: 'none',
      headingFont: "var(--font-display), 'Helvetica Neue', Arial, sans-serif",
      bodyFont: "var(--font-sans), system-ui, sans-serif",
      headingWeight: 800,
      headingTracking: '-0.02em',
      headingTransform: 'uppercase',
      density: 'airy',
    },
    layout: {
      header: 'editorial',
      footer: 'editorial',
      productCard: 'editorial',
      productDetail: 'stickyPanel',
      gridColumns: { base: 2, sm: 2, lg: 3, xl: 4 },
      productAspect: '3 / 4',
    },
    sections: [
      { id: 'hero', kind: 'hero', variant: 'fullBleed', removable: false, defaultVisible: true },
      {
        id: 'new-arrivals',
        kind: 'productRow',
        variant: 'editorialRow',
        title: 'New arrivals',
        subtitle: 'Just landed in store',
        source: 'newest',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'categories',
        kind: 'categories',
        variant: 'editorialTiles',
        title: 'The collections',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'collection-banner',
        kind: 'collectionBanner',
        variant: 'splitFrame',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'trending',
        kind: 'productRow',
        variant: 'editorialRow',
        title: 'Trending now',
        subtitle: 'What the city is wearing',
        source: 'popular',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'featured',
        kind: 'productRow',
        variant: 'editorialGrid',
        title: 'Featured',
        subtitle: 'Hand-picked by the store',
        source: 'featured',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      { id: 'brands', kind: 'brands', variant: 'marquee', title: 'Brands we carry', removable: true, defaultVisible: true },
      { id: 'offers', kind: 'offers', variant: 'ticker', removable: true, defaultVisible: true },
      {
        id: 'testimonials',
        kind: 'testimonials',
        variant: 'quoteRow',
        title: 'From the fitting room',
        removable: true,
        defaultVisible: true,
      },
      { id: 'trust', kind: 'trustStrip', variant: 'minimal', removable: true, defaultVisible: true },
    ],
  },

  // ══════════════════════════════════════════════════════ silk editorial ══
  {
    id: 'silk-editorial',
    name: 'Silk Editorial',
    version: 1,
    group: 'Fashion',
    tagline: 'Elegant womenswear, styled like a magazine',
    description:
      'A serif voice, generous whitespace and collection-led browsing. Designed for sarees, ' +
      'textiles and boutiques where the fabric is the argument.',
    businessTypes: [
      "Women's Wear",
      'Womenswear',
      'Textile',
      'Saree',
      'Boutique',
      'Jewellery',
      'Home & Lifestyle',
    ],
    swatches: ['#7b2d43', '#d9a7a0', '#fdf8f4'],
    badges: ['Premium'],
    theme: {
      primaryColor: '#7b2d43',
      accentColor: '#c98b7d',
      surfaceColor: '#fdf9f5',
      contentColor: '#2b2020',
      radius: 'sm',
      headingFont: "var(--font-serif), Georgia, 'Times New Roman', serif",
      bodyFont: 'var(--font-sans), system-ui, sans-serif',
      headingWeight: 500,
      headingTracking: '-0.01em',
      headingTransform: 'none',
      density: 'airy',
    },
    layout: {
      header: 'classic',
      footer: 'columns',
      productCard: 'portrait',
      productDetail: 'stackedGallery',
      gridColumns: { base: 2, sm: 2, lg: 3, xl: 3 },
      productAspect: '4 / 5',
    },
    sections: [
      { id: 'hero', kind: 'hero', variant: 'lifestyle', removable: false, defaultVisible: true },
      {
        id: 'categories',
        kind: 'categories',
        variant: 'roundedRail',
        title: 'Shop by collection',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'featured',
        kind: 'productRow',
        variant: 'gallery',
        title: 'The featured edit',
        subtitle: 'Chosen for this season',
        source: 'featured',
        limit: 6,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'collection-banner',
        kind: 'collectionBanner',
        variant: 'centered',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'new-arrivals',
        kind: 'productRow',
        variant: 'gallery',
        title: 'New this week',
        subtitle: 'Fresh off the loom',
        source: 'newest',
        limit: 6,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'editorial',
        kind: 'editorial',
        variant: 'letter',
        title: 'Our story',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'best-sellers',
        kind: 'productRow',
        variant: 'gallery',
        title: 'Most loved',
        subtitle: 'What our customers keep coming back for',
        source: 'popular',
        limit: 6,
        removable: true,
        defaultVisible: true,
      },
      { id: 'offers', kind: 'offers', variant: 'cards', title: 'Seasonal offers', removable: true, defaultVisible: true },
      { id: 'trust', kind: 'trustStrip', variant: 'bordered', removable: true, defaultVisible: true },
      { id: 'newsletter', kind: 'newsletter', variant: 'centered', removable: true, defaultVisible: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════ spec grid ══
  {
    id: 'spec-grid',
    name: 'Spec Grid',
    version: 1,
    group: 'Technology',
    tagline: 'Phones and electronics, specs first',
    description:
      'Dense, scannable and comparison-friendly. Brand navigation, specification chips on ' +
      'every card and an EMI-aware buy box — the way people actually shop for a handset.',
    businessTypes: ['Mobile Shop', 'Electronics', 'Computer Accessories'],
    swatches: ['#0b57d0', '#00b4a6', '#f1f5f9'],
    badges: ['Popular'],
    theme: {
      primaryColor: '#0b57d0',
      accentColor: '#00a99a',
      surfaceColor: '#f4f6fa',
      contentColor: '#111827',
      radius: 'md',
      headingFont: 'var(--font-tech), var(--font-sans), system-ui, sans-serif',
      bodyFont: 'var(--font-sans), system-ui, sans-serif',
      headingWeight: 700,
      headingTracking: '-0.02em',
      headingTransform: 'none',
      density: 'compact',
    },
    layout: {
      header: 'utility',
      footer: 'columns',
      productCard: 'spec',
      productDetail: 'specSheet',
      gridColumns: { base: 2, sm: 3, lg: 4, xl: 5 },
      productAspect: '1 / 1',
    },
    sections: [
      { id: 'hero', kind: 'hero', variant: 'deviceSplit', removable: false, defaultVisible: true },
      { id: 'trust', kind: 'trustStrip', variant: 'emi', removable: true, defaultVisible: true },
      { id: 'brands', kind: 'brands', variant: 'tiles', title: 'Shop by brand', removable: true, defaultVisible: true },
      {
        id: 'categories',
        kind: 'categories',
        variant: 'iconGrid',
        title: 'Browse categories',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'best-sellers',
        kind: 'productRow',
        variant: 'denseGrid',
        title: 'Best sellers',
        subtitle: 'Most bought this month',
        source: 'popular',
        limit: 10,
        removable: true,
        defaultVisible: true,
      },
      { id: 'offers', kind: 'offers', variant: 'cards', title: "Today's offers", removable: true, defaultVisible: true },
      {
        id: 'featured',
        kind: 'productRow',
        variant: 'denseGrid',
        title: 'Featured devices',
        subtitle: 'Recommended by the store',
        source: 'featured',
        limit: 10,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'collection-banner',
        kind: 'collectionBanner',
        variant: 'wideStrip',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'new-arrivals',
        kind: 'productRow',
        variant: 'denseGrid',
        title: 'Just arrived',
        subtitle: 'Newest stock on the shelf',
        source: 'newest',
        limit: 10,
        removable: true,
        defaultVisible: true,
      },
    ],
  },

  // ═════════════════════════════════════════════════════════════════ glow ══
  {
    id: 'glow-beauty',
    name: 'Glow',
    version: 1,
    group: 'Beauty',
    tagline: 'Beauty and skincare with a soft touch',
    description:
      'Warm neutrals, rounded surfaces and an ingredient-led product story. Made for ' +
      'cosmetics counters, skincare and personal care.',
    businessTypes: ['Cosmetics', 'Beauty & Personal Care'],
    swatches: ['#b0546a', '#f0c9c0', '#fffaf7'],
    badges: ['New'],
    theme: {
      primaryColor: '#b0546a',
      accentColor: '#e0a08f',
      surfaceColor: '#fffaf7',
      contentColor: '#3b2b2e',
      radius: 'lg',
      headingFont: "var(--font-serif), Georgia, 'Times New Roman', serif",
      bodyFont: 'var(--font-sans), system-ui, sans-serif',
      headingWeight: 600,
      headingTracking: '-0.015em',
      headingTransform: 'none',
      density: 'regular',
    },
    layout: {
      header: 'soft',
      footer: 'soft',
      productCard: 'soft',
      productDetail: 'stackedGallery',
      gridColumns: { base: 2, sm: 3, lg: 4, xl: 4 },
      productAspect: '1 / 1',
    },
    sections: [
      { id: 'hero', kind: 'hero', variant: 'softCurve', removable: false, defaultVisible: true },
      {
        id: 'categories',
        kind: 'categories',
        variant: 'roundedRail',
        title: 'Shop by concern',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'best-sellers',
        kind: 'productRow',
        variant: 'softGrid',
        title: 'Best sellers',
        subtitle: 'The shelf favourites',
        source: 'popular',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      { id: 'trust', kind: 'trustStrip', variant: 'pills', removable: true, defaultVisible: true },
      {
        id: 'featured',
        kind: 'productRow',
        variant: 'softGrid',
        title: 'Trending now',
        subtitle: 'What everyone is reaching for',
        source: 'featured',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'collection-banner',
        kind: 'collectionBanner',
        variant: 'centered',
        removable: true,
        defaultVisible: true,
      },
      { id: 'brands', kind: 'brands', variant: 'tiles', title: 'Brands in store', removable: true, defaultVisible: true },
      {
        id: 'editorial',
        kind: 'editorial',
        variant: 'ritual',
        title: 'Build your routine',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'new-arrivals',
        kind: 'productRow',
        variant: 'softGrid',
        title: 'New in',
        subtitle: 'Fresh on the counter',
        source: 'newest',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      { id: 'offers', kind: 'offers', variant: 'cards', title: 'Offers', removable: true, defaultVisible: true },
      { id: 'newsletter', kind: 'newsletter', variant: 'soft', removable: true, defaultVisible: true },
    ],
  },

  // ══════════════════════════════════════════════════════════════ daily ═══
  {
    id: 'daily-cart',
    name: 'Daily Cart',
    version: 1,
    group: 'Retail',
    tagline: 'Everyday retail, built for speed',
    description:
      'Dense category chips, compact cards and a short path to the basket. For grocery, ' +
      'stationery, fancy stores and general retail where people know what they came for.',
    businessTypes: [
      'Grocery',
      'General Store',
      'General Retail',
      'Fancy Store',
      'Stationery',
      'Home & Kitchen',
    ],
    swatches: ['#0f7a3d', '#f5a524', '#f6f8f5'],
    theme: {
      primaryColor: '#0f7a3d',
      accentColor: '#f5a524',
      surfaceColor: '#f6f8f5',
      contentColor: '#14231a',
      radius: 'md',
      headingFont: 'var(--font-sans), system-ui, sans-serif',
      bodyFont: 'var(--font-sans), system-ui, sans-serif',
      headingWeight: 700,
      headingTracking: '-0.015em',
      headingTransform: 'none',
      density: 'compact',
    },
    layout: {
      header: 'utility',
      footer: 'compact',
      productCard: 'compact',
      productDetail: 'gallerySplit',
      gridColumns: { base: 2, sm: 3, lg: 5, xl: 6 },
      productAspect: '1 / 1',
    },
    sections: [
      { id: 'hero', kind: 'hero', variant: 'compactSearch', removable: false, defaultVisible: true },
      {
        id: 'categories',
        kind: 'categories',
        variant: 'chips',
        title: 'Shop by aisle',
        removable: true,
        defaultVisible: true,
      },
      { id: 'offers', kind: 'offers', variant: 'ticker', removable: true, defaultVisible: true },
      {
        id: 'best-sellers',
        kind: 'productRow',
        variant: 'denseGrid',
        title: 'Bought most often',
        subtitle: 'Your neighbourhood staples',
        source: 'popular',
        limit: 12,
        removable: true,
        defaultVisible: true,
      },
      { id: 'trust', kind: 'trustStrip', variant: 'minimal', removable: true, defaultVisible: true },
      {
        id: 'featured',
        kind: 'productRow',
        variant: 'denseGrid',
        title: "Today's picks",
        subtitle: 'Fresh from the shop',
        source: 'featured',
        limit: 12,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'collection-banner',
        kind: 'collectionBanner',
        variant: 'wideStrip',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'new-arrivals',
        kind: 'productRow',
        variant: 'denseGrid',
        title: 'New on the shelf',
        source: 'newest',
        limit: 12,
        removable: true,
        defaultVisible: true,
      },
    ],
  },

  // ════════════════════════════════════════════════════════════ pawsome ═══
  {
    id: 'pawsome',
    name: 'Pawsome',
    version: 1,
    group: 'Specialised',
    tagline: 'Friendly and playful, for pets and gifting',
    description:
      'Rounded shapes, warm colour and a browse-by-companion layout. Suits pet shops, gift ' +
      'stores and kidswear, where the shopping is joyful rather than transactional.',
    businessTypes: ['Pet Shop', 'Gift Shop', 'Kidswear', "Kids Wear", 'Toys'],
    swatches: ['#1f8a8c', '#f79c42', '#fef8ee'],
    badges: ['New'],
    theme: {
      primaryColor: '#1f8a8c',
      accentColor: '#f79c42',
      surfaceColor: '#fef8ee',
      contentColor: '#1f2933',
      radius: 'full',
      headingFont: 'var(--font-rounded), var(--font-sans), system-ui, sans-serif',
      bodyFont: 'var(--font-rounded), var(--font-sans), system-ui, sans-serif',
      headingWeight: 800,
      headingTracking: '-0.02em',
      headingTransform: 'none',
      density: 'regular',
    },
    layout: {
      header: 'playful',
      footer: 'soft',
      productCard: 'soft',
      productDetail: 'gallerySplit',
      gridColumns: { base: 2, sm: 3, lg: 4, xl: 4 },
      productAspect: '1 / 1',
    },
    sections: [
      { id: 'hero', kind: 'hero', variant: 'playful', removable: false, defaultVisible: true },
      {
        id: 'categories',
        kind: 'categories',
        variant: 'bubbles',
        title: 'Who are we shopping for?',
        removable: true,
        defaultVisible: true,
      },
      { id: 'trust', kind: 'trustStrip', variant: 'pills', removable: true, defaultVisible: true },
      {
        id: 'best-sellers',
        kind: 'productRow',
        variant: 'softGrid',
        title: 'Tail-wagging favourites',
        subtitle: 'The things they ask for twice',
        source: 'popular',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'collection-banner',
        kind: 'collectionBanner',
        variant: 'splitFrame',
        removable: true,
        defaultVisible: true,
      },
      {
        id: 'featured',
        kind: 'productRow',
        variant: 'softGrid',
        title: 'Featured picks',
        subtitle: 'Chosen by the shop',
        source: 'featured',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      { id: 'offers', kind: 'offers', variant: 'cards', title: 'Treats and offers', removable: true, defaultVisible: true },
      {
        id: 'new-arrivals',
        kind: 'productRow',
        variant: 'softGrid',
        title: 'Just unpacked',
        source: 'newest',
        limit: 8,
        removable: true,
        defaultVisible: true,
      },
      { id: 'brands', kind: 'brands', variant: 'tiles', title: 'Brands we trust', removable: true, defaultVisible: true },
      { id: 'newsletter', kind: 'newsletter', variant: 'soft', removable: true, defaultVisible: true },
    ],
  },
] as const;

/**
 * The template a store falls back to.
 *
 * Chosen because it is the most neutral of the six: any catalogue reads
 * acceptably in it, which is what a fallback has to guarantee.
 */
export const FALLBACK_TEMPLATE_ID = 'daily-cart';
