import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

export interface TenantMigration {
  /** Directory name, e.g. `0002_constraints_and_search`. Sorts lexicographically. */
  name: string;
  sql: string;
  /** SHA-256 of the SQL; a changed checksum on an applied migration is a hard error. */
  checksum: string;
}

/**
 * Tenant migrations are plain, versioned SQL rather than `prisma migrate`.
 *
 * Reasoning (docs/DECISION_LOG.md ADR-006): provisioning a tenant has to apply
 * migrations from *inside* the API process, against a database whose name is
 * only known at runtime. Shelling out to the Prisma CLI per tenant would mean
 * shipping the CLI into the production image and spawning a Node process per
 * provision. Reading `.sql` files and applying them in a transaction is faster,
 * observable, and works identically in a worker and in a test.
 *
 * The SQL itself is still *generated* from `tenant/schema.prisma` via
 * `prisma migrate diff`, so the schema stays the single source of truth.
 */
const CANDIDATE_DIRS = [
  // Compiled: database/dist/migrations.js -> database/tenant/migrations
  resolve(__dirname, '..', 'tenant', 'migrations'),
  // Source (ts-node / jest): database/src/migrations.ts -> database/tenant/migrations
  resolve(__dirname, '..', '..', 'tenant', 'migrations'),
  // Docker image layout
  resolve(process.cwd(), 'database', 'tenant', 'migrations'),
];

export function resolveTenantMigrationsDir(override?: string): string {
  const candidates = override ? [resolve(override), ...CANDIDATE_DIRS] : CANDIDATE_DIRS;
  for (const dir of candidates) {
    if (existsSync(dir)) return dir;
  }
  throw new Error(
    `Tenant migrations directory not found. Looked in:\n  ${candidates.join('\n  ')}`,
  );
}

/**
 * Loads every migration in lexicographic order. The numeric prefix is what
 * guarantees deterministic ordering, so new migrations must keep using it.
 */
export function loadTenantMigrations(dirOverride?: string): TenantMigration[] {
  const dir = resolveTenantMigrationsDir(dirOverride);

  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => /^\d{4}_/.test(name))
    .sort()
    .map((name) => {
      const file = join(dir, name, 'migration.sql');
      if (!existsSync(file)) {
        throw new Error(`Migration ${name} is missing migration.sql`);
      }
      const sql = readFileSync(file, 'utf8');
      return { name, sql, checksum: checksumOf(sql) };
    });
}

export function checksumOf(sql: string): string {
  // Normalise line endings so a Windows checkout does not invalidate checksums.
  return createHash('sha256').update(sql.replace(/\r\n/g, '\n'), 'utf8').digest('hex');
}

/** The version a freshly provisioned tenant database ends up at. */
export function latestTenantSchemaVersion(dirOverride?: string): string {
  const migrations = loadTenantMigrations(dirOverride);
  const last = migrations[migrations.length - 1];
  if (!last) throw new Error('No tenant migrations found');
  return last.name;
}

/**
 * Splits a migration file into individually executable statements.
 *
 * Written by hand rather than with a SQL parser because our migrations are
 * generated by Prisma plus hand-written DDL — no procedural blocks, no
 * user-defined functions. It handles line comments, block comments and quoted
 * literals, which is everything our SQL actually contains.
 */
export function splitSqlStatements(sql: string): string[] {
  const statements: string[] = [];
  let current = '';
  let inSingle = false;
  let inDouble = false;
  let inLineComment = false;
  let inBlockComment = false;
  let dollarTag: string | null = null;

  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    const next = sql[i + 1];

    if (inLineComment) {
      if (ch === '\n') inLineComment = false;
      current += ch;
      continue;
    }
    if (inBlockComment) {
      current += ch;
      if (ch === '*' && next === '/') {
        current += next;
        i++;
        inBlockComment = false;
      }
      continue;
    }
    if (dollarTag) {
      current += ch;
      if (ch === '$' && sql.startsWith(dollarTag, i)) {
        current += sql.slice(i + 1, i + dollarTag.length);
        i += dollarTag.length - 1;
        dollarTag = null;
      }
      continue;
    }

    if (!inSingle && !inDouble) {
      if (ch === '-' && next === '-') {
        inLineComment = true;
        current += ch;
        continue;
      }
      if (ch === '/' && next === '*') {
        inBlockComment = true;
        current += ch;
        continue;
      }
      if (ch === '$') {
        const match = /^\$[A-Za-z_]*\$/.exec(sql.slice(i));
        if (match) {
          dollarTag = match[0];
          current += dollarTag;
          i += dollarTag.length - 1;
          continue;
        }
      }
    }

    if (ch === "'" && !inDouble) {
      // '' inside a string literal is an escaped quote, not a terminator.
      if (inSingle && next === "'") {
        current += "''";
        i++;
        continue;
      }
      inSingle = !inSingle;
      current += ch;
      continue;
    }
    if (ch === '"' && !inSingle) {
      inDouble = !inDouble;
      current += ch;
      continue;
    }

    if (ch === ';' && !inSingle && !inDouble) {
      const trimmed = current.trim();
      if (trimmed) statements.push(trimmed);
      current = '';
      continue;
    }

    current += ch;
  }

  const tail = current.trim();
  if (tail) statements.push(tail);

  // Drop fragments that are nothing but comments/whitespace.
  return statements.filter((s) => stripComments(s).length > 0);
}

function stripComments(sql: string): string {
  return sql
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/--[^\n]*/g, '')
    .trim();
}

/** True when a statement cannot run inside a transaction block. */
export function requiresAutocommit(statement: string): boolean {
  return /CREATE\s+(UNIQUE\s+)?INDEX\s+CONCURRENTLY/i.test(statement);
}
